### PR TITLE
Port from GStreamer Gst.Message.structure to get_structure

### PR DESCRIPTION
**Pull request by Creatune**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  I understand from a private message that you did not test.  The repository is a set of example programs, some of which contain the activity directory needed to run them.  Test them individually.  Perhaps only the GTK 3 examples need this change, as GStreamer may not have changed for the GTK 2 environment.  See the book for how else they must be tested.

**Comment by Creatune** [comment]
I tested the activities that use gtk3. They seem to be working fine. A few gave an error regarding porting to TelepathyGlib (before and after porting). But the others worked fine without any errors. So should I go ahead and port the activities to TelepathyGLib or should I consider this task done? Thank you :)

**Comment by jdsimmons** [comment]
Joshi,

As the original author of these examples, some of them were written to
demonstrate the use of Telepathy for making shared activities and they
would be no use to anyone without this functionality. The relevant chapter
of the book is here:

http://write.flossmanuals.net/make-your-own-sugar-activities/making-shared-activities/


I have not been actively involved in Sugar Labs for years, but there was a
time when this manual was the most complete source of information on making
Sugar Activities. A group of 10 or so people even translated the book into
Spanish:

https://archive.org/details/ComoHacerUnaActividadSugar

(The book seems to have vanished from the Floss Manuals website, but you
can get the PDF from archive.org)

James Simmons

**Comment by quozl** [comment]
@Creatune, thanks for that.  Please add the testing or not testing detail to the commit message (e.g. git commit --amend ; git push --force).  No need to port to TelepathyGLib as part of this pull request.

**Pull request merged**
